Use only power instead of power + energy in the definition of the baselines and measurements
euniversal/umei-api-specification pull request #11
Opened 2021-11-05 11:31 UTC by cdmNSIDE

… baselines and measurements

2021-11-08 13:48 UTC, narve requested changes
Why were all fields changed to required? 

Note that there are different levels of required. Even though a field might be required when storing (e.g. in a non-nullable database column), that does not mean that the fields should be mandatory from a user perspective. The most obvious is "Id", which is typically NOT provided by the client (doing the POST) but by the server (and included in the response).

2021-11-09 13:53 UTC, cdmNSIDE commented
I will remove my modifications associated to the required / nullable fields.
If needed I will address it in another PR

2021-11-10 11:57 UTC, narve approved these changes

2021-11-10 13:08 UTC, ArnaudDebray approved these changes

2021-11-10 14:34 UTC, merged