chore/rename-assetportfolio
euniversal/umei-api-specification pull request #6
Opened 2021-11-04 12:40 UTC by narve

2021-11-08 11:19 UTC, narve commented
Any comments on this one? It is not important from our perspective (we still use AssetPortfolio in our API), but it would be nice to get other participants comments/review.

2021-11-09 08:08 UTC, narve commented
@cdmNSIDE @ArnaudDebray @lde-nside if no objections, please approve this PR. If any objections, please comment.

2021-11-09 16:26 UTC, cdmNSIDE requested changes

2021-11-09 16:26 UTC, cdmNSIDE commented on umei-openapi.json
> +          "PortfolioId": {
Should it start with a lower case ?

2021-11-09 16:26 UTC, cdmNSIDE commented on umei-openapi.json
> +          "PortfolioId": {
Should it start with a lower case ?

2021-11-09 16:26 UTC, cdmNSIDE commented on umei-openapi.json
> +          "PortfolioId": {
Should it start with a lower case ?

2021-11-09 16:26 UTC, cdmNSIDE commented on umei-openapi.json
>          "additionalProperties": true
Shouldn't we add a description to explain what a portfolio is ? Does it still group several assets ?

2021-11-09 16:26 UTC, cdmNSIDE commented on umei-openapi.json
>              "description": "The asset portfolio for which this order applies.  \r\nRequired on create for sell orders.\r\nNot updateable.",
Update this description as well ?

2021-11-10 12:50 UTC, ArnaudDebray commented
I don't have a strong opinion on this. To me, AssetPortfolio is clear. We can change it to portfolio but I don't see a big added value

2021-11-10 16:39 UTC, cdmNSIDE submitted a review, later dismissed

2021-11-11 09:31 UTC, narve commented
@cdmNSIDE @ArnaudDebray @lde-nside ok to merge this one? I've fixed the conflicts now.

2021-11-15 09:49 UTC, cdmNSIDE approved these changes

2021-11-15 10:03 UTC, ArnaudDebray approved these changes

2021-11-15 10:04 UTC, merged